---
- name: Ansible less19
  hosts: all
  any_errors_fatal : true
  become: yes
    

  tasks:
  - name: Task number1
    yum: name=treeee state=latest
    ignore_errors: yes

  - name: Task Number2
    shell: cat /home/dlap/myfile.txt
    register: results
#    failed_when: results.rc == 0
#    failed_when: "'World' in results.stdout"

  - debug:
      var: results

  - name: Task Number3
    shell: echo provent mit111
